export const actionType = {
    NHAN_DANH_MUC_HE_THONG_RAP:'NHAN_DANH_MUC_HE_THONG_RAP',
    NHAN_THONG_TIN_CUM_RAP: 'NHAN_THONG_TIN_CUM_RAP',
    NHAN_THONG_TIN_LICH_CHIEU_HE_THONG_RAP:'NHAN_THONG_TIN_LICH_CHIEU_HE_THONG_RAP',
    NHAN_THONG_TIN_LICH_CHIEU_PHIM:'NHAN_THONG_TIN_LICH_CHIEU_PHIM'
}