export const actionType =
{
    DANG_NHAP:'DANG_NHAP',
    DANG_KY:'DANG_KY',
    NGUOI_DANG_NHAP:'NGUOI_DANG_NHAP',
    NHAN_DANH_SACH_NGUOI_DUNG:'NHAN_DANH_SACH_NGUOI_DUNG',
    CHINH_SUA_NGUOI_DUNG:'CHINH_SUA_NGUOI_DUNG',
    // XOA_NGUOI_DUNG:'XOA_NGUOI_DUNG',
    LAY_DANH_SACH_NGUOI_TAO:'LAY_DANH_SACH_NGUOI_TAO'
}
